### PR TITLE
Fix csv course data bundling

### PR DESCRIPTION
**Pull request by drewvolz**
Should let us close https://github.com/StoDevX/course-data/pull/5

### CODE REVIEW

**Comment by drewvolz** [comment]
Build error: 

"TypeError: sequence item 0: expected str instance, dict found" in `course-data-tools/lib/csvify.py`, line 15, in csvify

https://github.com/StoDevX/course-data-tools/blob/23265d6bc2db8ad2bf04cdcf1dd14ee955abde7a/lib/csvify.py#L14-L15

```bash
# update bundled information for public consumption
python3 ../bundle.py --out-dir ../course-data --format json --format xml --format csv
concurrent.futures.process._RemoteTraceback: 
"""
TypeError: sequence item 0: expected str instance, dict found
```

**Comment by hawkrives** [comment]
Yes, there is a bug in the build process, which is why the CSV output was disabled.

**Comment by drewvolz** [comment]
Ah, you disabled that [here](https://github.com/StoDevX/course-data-tools/commit/56102d3ea9abb866bad12016ecaadbe5713645b3).

**Comment by drewvolz** [comment]
@hawkrives do you want to dig into this?

**Comment by drewvolz** [comment]
CSV output is now fixed. Converted each element to a string first to fix the export.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
